### ISSUE TITLE
loss_cls and loss_seq

### ISSUE THREAD

**Issue by Guo-Xiaoqing** [svip-lab/WeakSVR#2]
Thanks for sharing the code. In Eq. 13 of the manuscript, only two losses are used in training. However, in the code, it seems that four losses are leveraged, including loss_cls and loss_seq. Since the paper focuses on unaligned text for videos, I was wondering what is the label in loss_cls. Looking forward to your reply. Thanks.

**Comment by Ironieser** [comment]
Hi，
Sorry for unclear codes, we will update more detail and explains.
 The loss_cls and loss_seq are used in supervised, which means we utilized the extra class information to train the model. Theses losses are follow SVIP, and we adjust the  
seq loss to improve the performance of model.
