### ISSUE TITLE
parameter of 'text_label_num' 

### ISSUE THREAD

**Issue by Guo-Xiaoqing** [svip-lab/WeakSVR#4]
Hello, I was wondering what is the parameter of 'text_label_num' in the function of 'compute_gumbel_loss'? Thanks.

**Comment by Ironieser** [comment]
Hi, 
Refer to 'clip_dataset.py.'
It is the " sample['label_token_phrase1']". 
This param describes the number of phrases in one video. Hence, we could uniformly split the frame-text sim matrix by calculating the ratio of the number of frames to the number of phrases.

https://github.com/svip-lab/WeakSVR/blob/80c1c4f357c433258352fdfd9869a672d5e3711a/Data/clip_dataset.py#L103
 https://github.com/svip-lab/WeakSVR/blob/80c1c4f357c433258352fdfd9869a672d5e3711a/Data/clip_dataset.py#L108

More codes to explain this question,
```python
label_phrase_num1 = sample['label_token_phrase1'][1].to(local_rank, non_blocking=True)

loss_gumbel1 = compute_gumbel_loss(seq_features1, text_feature_phrase1, label_phrase_num1, logit_scale1_2,max_seq_length=MAX_SEQ_LENGTH, gt_type=args.gt_type,labels1=sample['labels1_raw'])
```

If you need more code of train steps or others, please wait a few weeks. We are revising the code, and we will release the train.py, checkpoints and add more annotations.

Thanks
